let e = document.getElementById("elzero");
console.log(e);
e = document.getElementsByClassName("element")[0];
console.log(e);
e = document.getElementsByName("js")[0];
console.log(e);
e = document.getElementsByTagName("div")[0];
console.log(e);
e = document.querySelector("div");
console.log(e);
e = document.querySelector("#elzero");
console.log(e);
e = document.querySelector(".element");
console.log(e);
e = document.querySelector(`[name="js"]`);
console.log(e);
e = document.querySelectorAll("div")[0];
console.log(e);
e = document.querySelectorAll("#elzero")[0];
console.log(e);
e = document.querySelectorAll(".element")[0];
console.log(e);
e = document.querySelectorAll(`[name="js"]`)[0];
console.log(e);
e = document.body.firstChild;
console.log(e);
e = document.body.firstElementChild;
console.log(e);
e = document.body.children[0];
console.log(e);
e = document.body.childNodes[0];
console.log(e);
